#!/usr/bin/env node
/**
 * Generates dist/ from src/. The JSON in src/ is the only source of truth:
 * CSS, the Tailwind bridge and the JS export are all emitted from it, so a
 * colour cannot be right in one consumer and stale in another.
 *
 * Also acts as the contract check. Every theme must declare exactly the same
 * semantic keys as every other, so an app can never quietly drop a token and
 * inherit whatever the previous theme happened to leave behind.
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync, cpSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const src = join(root, "src");
const dist = join(root, "dist");

const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const stamp = (what) =>
  `/* ${what}\n` +
  ` * Generated by obvious v${pkg.version}. Do not edit by hand:\n` +
  ` * change src/ in trev-delivers/obvious and re-run \`npm run build\`.\n` +
  ` */\n\n`;

const isComment = (k) => k === "$comment";
const read = (p) => JSON.parse(readFileSync(p, "utf8"));

const primitives = read(join(src, "primitives.json"));
const themes = readdirSync(join(src, "themes"))
  .filter((f) => f.endsWith(".json"))
  .map((f) => read(join(src, "themes", f)))
  .sort((a, b) => a.name.localeCompare(b.name));

/* ---- contract check ------------------------------------------------- */

const shape = (t) =>
  ["dial", "font", "color"].flatMap((group) =>
    Object.keys(t[group] ?? {}).filter((k) => !isComment(k)).map((k) => `${group}.${k}`),
  );

const reference = themes.find((t) => t.name === "core");
if (!reference) throw new Error("themes/core.json is the reference theme and must exist");
const expected = shape(reference).sort();

const problems = [];
for (const theme of themes) {
  const actual = shape(theme).sort();
  for (const key of expected) if (!actual.includes(key)) problems.push(`${theme.name}: missing ${key}`);
  for (const key of actual) if (!expected.includes(key)) problems.push(`${theme.name}: unknown ${key} (not in core)`);
}
if (problems.length) {
  console.error("Theme contract broken:\n  " + problems.join("\n  "));
  process.exit(1);
}

/* ---- emit ------------------------------------------------------------ */

/** Flattens a primitive group into [cssVarName, value] pairs. */
function vars(group, prefix) {
  const out = [];
  for (const [key, value] of Object.entries(group)) {
    if (isComment(key)) continue;
    out.push([`${prefix}-${key}`, value]);
  }
  return out;
}

const primitiveVars = [
  ...vars(primitives.space, "--ds-space"),
  ...vars(primitives["space-fluid"], "--ds-space-fluid"),
  ["--ds-gutter", primitives.gutter],
  ["--ds-measure", primitives.measure],
  ["--ds-container", primitives.container],
  ...vars(primitives.text, "--ds-text"),
  ...vars(primitives.type, "--ds-type"),
  ...vars(primitives.leading, "--ds-leading"),
  ...vars(primitives.tracking, "--ds-tracking"),
  ...vars(primitives.weight, "--ds-weight"),
  ...vars(primitives.radius, "--ds-radius"),
  ...vars(primitives.border, "--ds-border"),
  ...vars(primitives.focus, "--ds-focus"),
  ...vars(primitives.duration, "--ds-duration"),
  ...vars(primitives.ease, "--ds-ease"),
  ...vars(primitives.shadow, "--ds-shadow"),
  ...vars(primitives.control, "--ds-control"),
  ...vars(primitives.z, "--ds-z"),
];

const themeVars = (theme) => [
  ...vars(theme.dial, "--ds"),
  ...vars(theme.font, "--ds-font"),
  ...vars(theme.color, "--ds-color"),
];

const block = (selector, pairs, indent = "  ") =>
  `${selector} {\n` + pairs.map(([k, v]) => `${indent}${k}: ${v};`).join("\n") + `\n}\n`;

mkdirSync(join(dist, "css", "themes"), { recursive: true });
mkdirSync(join(dist, "tailwind"), { recursive: true });
mkdirSync(join(dist, "js"), { recursive: true });

writeFileSync(
  join(dist, "css", "base.css"),
  stamp("obvious base — shared element behaviours. Opt-in; import after primitives and a theme.") +
    readFileSync(join(src, "base.css"), "utf8").replace(/^\/\*[\s\S]*?\*\/\n+/, ""),
);

writeFileSync(
  join(dist, "css", "primitives.css"),
  stamp("obvious primitives — shared by every app, identical everywhere.") +
    block(":root", primitiveVars),
);

for (const theme of themes) {
  writeFileSync(
    join(dist, "css", "themes", `${theme.name}.css`),
    stamp(`obvious theme: ${theme.label} — ${theme.description}`) + block(":root", themeVars(theme)),
  );
}

writeFileSync(
  join(dist, "css", "all-themes.css"),
  stamp("obvious — every theme, selectable with data-ds-theme. For the docs site; apps import their own theme file instead.") +
    themes.map((t) => block(`[data-ds-theme="${t.name}"]`, themeVars(t))).join("\n"),
);

/* The Tailwind v4 bridge. @theme inline means the utilities resolve through
   the --ds-* variables rather than snapshotting their values, so swapping a
   theme file at runtime still moves every utility with it. */
/* Additive only. An earlier version of this bridge mapped the system onto
   Tailwind's own named scales — --spacing-md, --radius-lg, --text-base,
   --shadow-sm — and silently changed what those utilities meant. Naming a
   --spacing-<name> key is the worst of them: Tailwind resolves max-w-md and
   friends through that same namespace, so max-w-md became 16px and every
   sheet and centred column in the consuming app collapsed. Tailwind's
   spacing scale is numeric (calc(var(--spacing) * n)) and is not ours to
   rename, so it is not mapped at all; reach for var(--ds-space-*) directly
   when a step is wanted.

   Everything that would collide is namespaced instead: rounded-ds-lg,
   text-ds-h1, ease-ds-out, shadow-ds-md. Opt-in, and impossible to confuse
   with the framework's own. Colours are new names rather than overrides, so
   they stay as they are, and --font-sans/--font-mono are a deliberate
   override: naming the app's typeface is the one thing the bridge should
   take over. */
const tw = [
  ["--color-bg", "var(--ds-color-bg)"],
  ["--color-bg-alt", "var(--ds-color-bg-alt)"],
  ["--color-surface", "var(--ds-color-surface)"],
  ["--color-surface-raised", "var(--ds-color-surface-raised)"],
  ["--color-surface-hover", "var(--ds-color-surface-hover)"],
  ["--color-border-subtle", "var(--ds-color-border-subtle)"],
  ["--color-border-strong", "var(--ds-color-border-strong)"],
  ["--color-ink", "var(--ds-color-text)"],
  ["--color-ink-dim", "var(--ds-color-text-dim)"],
  ["--color-ink-muted", "var(--ds-color-text-muted)"],
  ["--color-ink-inverse", "var(--ds-color-text-inverse)"],
  ["--color-accent", "var(--ds-color-accent)"],
  ["--color-accent-hover", "var(--ds-color-accent-hover)"],
  ["--color-accent-contrast", "var(--ds-color-accent-contrast)"],
  ["--color-accent-alt", "var(--ds-color-accent-alt)"],
  ["--color-success", "var(--ds-color-success)"],
  ["--color-warning", "var(--ds-color-warning)"],
  ["--color-danger", "var(--ds-color-danger)"],
  ["--color-info", "var(--ds-color-info)"],
  ["--font-display", "var(--ds-font-display)"],
  ["--font-sans", "var(--ds-font-sans)"],
  ["--font-mono", "var(--ds-font-mono)"],
  ["--font-script", "var(--ds-font-script)"],
  ...["xs", "sm", "md", "lg", "xl", "full"].map((s) => [`--radius-ds-${s}`, `var(--ds-radius-${s})`]),
  ...Object.keys(primitives.text).filter((k) => !isComment(k)).map((s) => [`--text-ds-${s}`, `var(--ds-text-${s})`]),
  ...Object.keys(primitives.ease).filter((k) => !isComment(k)).map((s) => [`--ease-ds-${s}`, `var(--ds-ease-${s})`]),
  ...Object.keys(primitives.shadow).filter((k) => !isComment(k)).map((s) => [`--shadow-ds-${s}`, `var(--ds-shadow-${s})`]),
];

writeFileSync(
  join(dist, "tailwind", "theme.css"),
  stamp("obvious — Tailwind v4 bridge. @import this after tailwindcss, alongside your theme file.") +
    block("@theme inline", tw),
);

/* Components. The interaction layer the family shares: the field assembly,
   the spinner-to-check morph, the gradient text, the thinking shimmer, the
   boot ring, the house link. Each ships as its own file so an app can take
   only what it uses, plus a bundle for the common case. Brookwood takes none
   of these on purpose — see README. */
mkdirSync(join(dist, "css", "components"), { recursive: true });
const components = readdirSync(join(src, "components"))
  .filter((f) => f.endsWith(".css"))
  .sort();

for (const file of components) {
  const body = readFileSync(join(src, "components", file), "utf8");
  const [, lead = "", rest = body] = body.match(/^(\/\*[\s\S]*?\*\/\n+)([\s\S]*)$/) ?? [];
  writeFileSync(
    join(dist, "css", "components", file),
    stamp(lead.replace(/^\/\*\s*|\s*\*\/$/g, "").trim().split("\n")[0]) + rest,
  );
}

writeFileSync(
  join(dist, "css", "components.css"),
  stamp("obvious components — the shared interaction layer. Import after primitives, a theme and base.") +
    components
      .map((f) => readFileSync(join(dist, "css", "components", f), "utf8"))
      .join("\n"),
);

cpSync(join(src, "js", "behaviours.js"), join(dist, "js", "behaviours.js"));

/* JS export, for the things that cannot read a stylesheet: the profile
   README's card.svg generator, OG image builders, canvas and WebGL code. */
const jsTokens = {
  version: pkg.version,
  primitives: Object.fromEntries(primitiveVars),
  themes: Object.fromEntries(themes.map((t) => [t.name, Object.fromEntries(themeVars(t))])),
};
writeFileSync(join(dist, "js", "tokens.json"), JSON.stringify(jsTokens, null, 2) + "\n");
writeFileSync(
  join(dist, "js", "tokens.js"),
  `// Generated by obvious v${pkg.version}. Do not edit by hand.\n` +
    `export const tokens = ${JSON.stringify(jsTokens, null, 2)};\n` +
    `export default tokens;\n`,
);

console.log(
  `obvious v${pkg.version}: ${primitiveVars.length} primitives, ` +
    `${themes.length} themes x ${themeVars(reference).length} semantic tokens, ` +
    `${components.length} components.`,
);
